#ifndef CONFIG_CUH_HZOEKYP0
#define CONFIG_CUH_HZOEKYP0

#define SMALL_ALIGNED_DATA_SET 64
#define SMALL_DATA_SET 1000 
#define MEDIUM_DATA_SET  100000
#define PERF_DATA_SET  100000000

#endif /* end of include guard: CONFIG_CUH_HZOEKYP0 */
